events {
    worker_connections 1024; # Sets the maximum simultaneous connections per worker
}

http {
log_format proxy_debug '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status $body_bytes_sent '
                       'to: $upstream_addr | upstream_status: $upstream_status | host: $proxy_host';

  include /etc/nginx/mime.types;



    # Use this format for your access log

  server {
    listen 80;
    listen [::]:80;
    server_name webviz.xyz;
    return 301 https://$host$request_uri/;
  }



  server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name webviz.xyz;

    error_log /var/log/nginx/debug-trace2.log debug;

    client_header_buffer_size 32k;

    ssl_certificate /etc/certs/fullchain.pem;
    ssl_certificate_key /etc/certs/privkey.pem;

    # Set up for good grade from SSL Labs test (https://www.ssllabs.com)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;
    root /usr/share/nginx/html/OHIFViewers/platform/app/dist;

    location /landing {

       add_header X-Debug-Matched-Location "landingBlock" always;

        access_log /var/log/nginx/landing_debug.log proxy_debug;

        alias /usr/share/nginx/html/landing/dist;
        add_header Cache-Control "no-cache" always;
        try_files $uri $uri/ =404;
    }
    location /ohifViewer/ {
    access_log /var/log/nginx/ohif2_debug.log proxy_debug;
    alias /usr/share/nginx/html/OHIFViewers/platform/app/dist/;
       # Inject debugging info into the response headers
        add_header X-Debug-Matched-Location "OHIF-Viewer/-Block" always;
        add_header X-Debug-Request-URI $request_uri always;
        add_header X-Debug-Document-Root $document_root always;
            try_files   $uri  index.html =404;

            add_header Cache-Control "no-cache" always;

    }


        location /auth {
                add_header X-Debug-Matched-Location "auth-Block" always;

          proxy_pass http://keycloak:8880;
          access_log /var/log/nginx/keycloak_debug.log proxy_debug;
          proxy_set_header Host $http_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Port $server_port;
          proxy_set_header X-Forwarded-Host webviz.xyz;
          proxy_buffer_size 128k;
          proxy_buffers 4 256k;
          proxy_busy_buffers_size 256k;

        }

  }
}

