events {
    worker_connections 1024; # Sets the maximum simultaneous connections per worker
}
http {
  include /etc/nginx/mime.types;



    # Use this format for your access log

  server {
    listen 80;
    listen [::]:80;
    server_name webviz.xyz;
    return 301 https://$host$request_uri;
  }


  server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name webviz.xyz;

    error_log /var/log/nginx/debug-trace2.log debug;

    client_header_buffer_size 32k;

    ssl_certificate /etc/certs/fullchain.pem;
    ssl_certificate_key /etc/certs/privkey.pem;

    # Set up for good grade from SSL Labs test (https://www.ssllabs.com)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;
    root /usr/share/nginx/html;
    location / {
        try_files $uri $uri/ =404;
    }
  }
}

